CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    email VARCHAR(60),
    login VARCHAR(60),
    name VARCHAR(60),
    birthday DATE);

CREATE TABLE IF NOT EXISTS friendship_status (
    friendship_status_id INTEGER PRIMARY KEY,
    status_name VARCHAR(10));

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users(id),
    friend_id INTEGER REFERENCES users(id),
    friendship_status_id INTEGER REFERENCES friendship_status(friendship_status_id));

CREATE TABLE IF NOT EXISTS film_rating (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR (60));

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER PRIMARY KEY,
    name VARCHAR(60),
    description VARCHAR(255),
    release_date DATE,
    duration INTEGER,
    rating_id INTEGER REFERENCES film_rating(rating_id));

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(60));

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER REFERENCES films(film_id),
    genre_id INTEGER REFERENCES genre(genre_id));

CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER REFERENCES films(film_id),
    user_id INTEGER REFERENCES users(id));