CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    email VARCHAR(60),
    login VARCHAR(60),
    name VARCHAR(60),
    birthday DATE);

CREATE TABLE IF NOT EXISTS friendship_status (
    friendship_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(10));

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users(id),
    friend_id INTEGER REFERENCES users(id),
    friendship_status_id INTEGER REFERENCES friendship_status(friendship_status_id),
    PRIMARY KEY (user_id, friend_id));

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name VARCHAR (60),
    mpa_description VARCHAR(255));

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER PRIMARY KEY,
    name VARCHAR(60),
    description VARCHAR(200),
    release_date DATE,
    duration LONG,
    mpa_id INTEGER REFERENCES mpa(mpa_id));

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(60));

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER REFERENCES films(film_id),
    genre_id INTEGER REFERENCES genre(genre_id),
    PRIMARY KEY (film_id, genre_id));

CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER REFERENCES films(film_id),
    user_id INTEGER REFERENCES users(id),
    PRIMARY KEY (film_id, user_id));